appParameters:
  # Events are written in a transaction and committed with this period.
  checkpointIntervalMs: "10000"

  # Set to false to allowing viewing metrics in Flink UI (may reduce performance).
  enableOperatorChaining: "false"
  # Read events from this stream.
  input-stream: "idracflatdata"
  input-startAtTail: "false"
  input-endAtTail: "false"
  input-minNumSegments: 1

jobName: IdracMetricsToTimescaleDB

# Flink app coordinates
mavenCoordinate:
  artifact: flinkprocessor
  group: io.pravega.idracsolution
  version: 0.1.0

flinkVersion: 1.13.2
imageRef:
  name: flink-1.13.2

localStorage:
  replicas: 2
  size: "20G"

volumes: []

parallelism: 1

jobManager:
  cpu: "500m"
  memory: "2048M"
  replicas: 1

taskManager:
  numberOfTaskSlots: 2
  replicas: 1
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

logging: {}
  #io.pravega: DEBUG
  #io.pravega.connectors: DEBUG
  #org.apache.flink: DEBUG
timescaledb:
  externalHost: sdp.sdp-demo.org
  imageRegistry: sdp-registry:31001/desdp
  hooks:
    image:
      repository: nautilus-kubectl
  # timescalDB HA image
  image:
    repository: timescaledb-ha
    tag: pg13.4-ts2.4.2-p0
  persistentVolumes:
    data:
      enabled: true
      size: 200Gi
      # sdp-local-path
      storageClass: "nfs"
    wal:
      enabled: true
      size: 5Gi
      # sdp-local-path
      storageClass: "nfs"
  database: tsdata
  patroni:
    postgresql:
      authentication:
        superuser:
          username: postgres
          password: password