apiVersion: "nautilus.dellemc.com/v1alpha1"
kind: "Project"
metadata:
  name: "idracsolution"
  namespace: "idracsolution"
spec:
  zookeeper:
    size: 3

  maven:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 10Gi

  storage:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 10Gi
