{
 "title": "IDRAC Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Rack",
    "label": "Rack",
    "query": "SHOW TAG VALUES FROM flat_metric_events_CUPS WITH KEY=RackLabel"
   },
   {
    "name": "IdracServer",
    "label": "IdracServer",
    "query": "SHOW TAG VALUES FROM flat_metric_events_CUPS WITH KEY=RemoteAddr WHERE \"RackLabel\" =~ /^$Rack$/ "
   }
  ]
 },
 "panels": [
  { "title": "Rack Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events",
     "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_CUPS\" WHERE (\"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ AND \"MetricId\" = 'CPUUsage') AND $timeFilter GROUP BY time($__interval), \"RemoteAddr\" fill(null)",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "CPUUsage" }
     ]
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events_CUPS",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "MemoryUsage" }
     ]
    }
   ]
  },
  {
   "title": "IDRAC Server Summary per Rack",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events",
     "query": "show tag values cardinality from \"flat_metric_events_CUPS\" with key = \"RemoteAddr\" WHERE (\"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IDRAC Server Total  ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events",
     "query": "show tag values cardinality from \"flat_metric_events_CUPS\" with key = \"RemoteAddr\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values cardinality from /^flat_metric_events/ with key = \"MetricId\"  WHERE (\"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "List of Metric IDs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_MetricId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "MetricId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events_Sensor",
     "query": "SELECT count(\"MetricValue\") FROM /^flat_metric_events_/ WHERE (\"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval), \"MetricId\" fill(previous)",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events_CUPS",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "CPUUsage" }
     ]
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events",
     "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_CUPS\" WHERE (\"Id\" = 'CUPS' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ AND \"MetricId\" = 'MemoryUsage') AND $timeFilter GROUP BY time($__interval), \"RemoteAddr\" fill(null)",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "MemoryUsage" }
     ]
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events_CUPS",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "IOUsage" }
     ]
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_RemoteAddr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "RemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flat_metric_events_CUPS",
     "select": [
      [
       { "params": [ "MetricValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Id", "operator": "=", "value": "CUPS" },
      { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
      { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
      { "condition": "AND", "key": "MetricId", "operator": "=", "value": "SystemUsage" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network TX",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_RemoteAddr $tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT derivative(last(\"MetricValue\"), 1m)/60 FROM \"flat_metric_events_NICStatistics\" WHERE (\"MetricId\" = 'TxBytes' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval), \"ContextID\", \"RemoteAddr\" fill(none)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "NICStatistics" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "TxUnicast" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Frame check sequence Errors",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_RemoteAddr $tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_NICStatistics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" },
         { "params": [ "FCS ERRORS" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "RxErrorPktFCSErrors" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Network RX",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_RemoteAddr $tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_NICStatistics",
       "query": "SELECT derivative(last(\"MetricValue\"), 1m)/60  FROM \"flat_metric_events_NICStatistics\" WHERE (\"MetricId\" = 'RxBytes' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval), \"ContextID\", \"RemoteAddr\" fill(none)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "RxBytes" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Power Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Consumptions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_RemoteAddr",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "WattsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Voltage Readings",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 11, "y": 3 },
     "targets": [
      {
       "alias": "$tag_RemoteAddr",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "Sensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "VoltageReading" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "repeat": "IdracServer",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    },
    {
     "title": "Temperature reading $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_Sensor\" WHERE (\"MetricId\" = 'TemperatureReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/) AND $timeFilter GROUP BY time($__interval),  \"ContextID\" fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "TemperatureReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU1Temp" },
        { "condition": "OR", "key": "ContextID", "operator": "=", "value": "iDRAC.Embedded.1#CPU2Temp" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PSU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "repeat": "IdracServer",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU temperature $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "Temperature" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
     "repeat": "IdracServer",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    },
    {
     "title": "PSU Fan Speed $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_PSUMetrics",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Temperature" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "PSUMetrics" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "FanSpeed" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Amps Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "repeat": "IdracServer",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Amps Total per Server $IdracServer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events_Sensor",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "MetricId", "operator": "=", "value": "AmpsReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Fan Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "repeat": "IdracServer",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Readings $IdracServer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ContextID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "RemoteAddr" ], "type": "tag" },
        { "params": [ "ContextID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flat_metric_events",
       "query": "SELECT mean(\"MetricValue\") FROM \"flat_metric_events_FanSensor\" WHERE (\"Id\" = 'FanSensor' AND \"MetricId\" = 'RPMReading' AND \"RackLabel\" =~ /^$Rack$/ AND \"RemoteAddr\" =~ /^$IdracServer$/ ) AND $timeFilter GROUP BY time($__interval),  \"ContextID\"  fill(null)",
       "select": [
        [
         { "params": [ "MetricValue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "Id", "operator": "=", "value": "FanSensor" },
        { "condition": "AND", "key": "MetricId", "operator": "=", "value": "RPMReading" },
        { "condition": "AND", "key": "RackLabel", "operator": "=~", "value": "/^$Rack$/" },
        { "condition": "AND", "key": "RemoteAddr", "operator": "=~", "value": "/^$IdracServer$/" },
        { "condition": "AND", "key": "ContextID", "operator": "=~", "value": "/^$Context$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}