apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    nautilus.dellemc.com/http-ingress: http
    nautilus.dellemc.com/http-ingress-name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    release: {{ .Release.Name }}-haproxy
  type: ClusterIP
