apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    release: {{ .Release.Name }}
  clusterIP: None
