apiVersion: v2
appVersion: 0.0.2
description: SDP Analytics for iDRAC solution
icon: http://local-helm-repo.kubeapps.svc.cluster.local/images/flink_squirrel_100_color.png
name: iDRAC-To-SDP
version: 0.0.2
dependencies:
  - name: ingest-gateway
    version: 1.0.x
