# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
--- 
appParameters: 
  enableOperatorChaining: "false"
appParametersJson: {}
clusterConfiguration: 
  restart-strategy: fixed-delay
  restart-strategy.fixed-delay.attempts: "1000000"
  restart-strategy.fixed-delay.delay: "30 s"
  taskmanager.memory.jvm-metaspace.size: "268435456"
  taskmanager.memory.task.off-heap.size: "0"
flinkVersion: "1.13.2"
imageRef: 
  name: flink-1.13.2
jobManager: 
  cpu: 1000m
  memory: 2048M
  replicas: 1
localStorage: 
  replicas: 2
  size: 5G
logging: {}
parallelism: 1
taskManager: 
  numberOfTaskSlots: 1
  replicas: 1
  resources: 
    limits: 
      cpu: 4000m
      memory: 4Gi
    requests: 
      cpu: 1000m
      memory: 4Gi
volumes: []
