{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: idracsolution
    component: gateway
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: idracsolution
      component: gateway
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: idracsolution
        component: gateway
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Namespace }}-pravega
      containers:
      - name: gateway
        image: {{ .Values.image.repository }}/gateway:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: PRAVEGA_CONTROLLER
            value: "{{ .Values.gateway.pravega.controller }}"
          - name: PRAVEGA_SCOPE
            value: "{{ .Release.Namespace }}"
          - name: PRAVEGA_STREAM
            value: "{{ .Values.gateway.pravega.stream }}"
          - name: PRAVEGA_MIN_NUM_SEGMENTS
            value: "{{ .Values.gateway.pravega.min_segments }}"
          - name: PRAVEGA_SCALE_FACTOR
            value: "{{ .Values.gateway.pravega.scale_factor }}"
          - name: PRAVEGA_TARGET_RATE_EVENTS_PER_SEC
            value: "{{ .Values.gateway.pravega.target_rate_events_per_sec }}"
---
{{- end }}
