{{- if .Values.flink.applications.switch.alertsToES }}
{{- $flink := .Values.flink -}}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "pravega-alerts-to-elasticsearch-job"
  labels:
    app: idracsolution
    component: PravegaMetricReportToElasticSearchJob
    release: {{ .Release.Name }}
spec:
  flinkVersion: {{ $flink.flinkVersion }}
  mavenCoordinate: {{ .Values.flink.applications.coordination.group }}:{{ .Values.flink.applications.coordination.artifact }}:{{ .Values.flink.applications.coordination.version }}

  parallelism: {{ .Values.flink.applications.parallelism }}

  state: started

  parameters:
    - name: jobClass
      value: "io.pravega.example.idracsolution.flinkprocessor.jobs.PravegaJsonToElasticSearchJob"
    - name: scope
      value: "idracsolution"
    - name: input-stream
      value: "alerts"

    # Elastic Search Parameters
    - name: elastic-sink
      value: "true"
    - name: elastic-delete-index
      value: "true"
    - name: elastic-host
      value: "idracsolution-elastic-stack-elasticsearch-client.idracsolution.svc.cluster.local"
    - name: elasticsearch-client
      value: "9200"
    - name: elastic-cluster
      value: "elasticsearch"
    - name: elastic-index
      value: "idracsolution-alerts"
    - name: elastic-type
      value: "Alert"

    # Flink Job Parameters
    - name: job.checkpointInterval
      value: "60000"
    - name: job.disableCheckpoint
      value: "false"
    - name: job.disableOperatorChaining
      value: "true"
    - name: rebalance
      value: "false"
{{- end }}
