{
 "title": "IDRAC Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Rack",
    "label": "Rack",
    "query": "{\"find\": \"terms\", \"field\": \"RackLabel.keyword\"}"
   },
   {
    "name": "IdracServer",
    "label": "IdracServer",
    "query": "{\"find\": \"terms\", \"field\": \"RemoteAddr.keyword\",  \"query\": \"RackLabel.keyword: $Rack\" }"
   }
  ]
 },
 "panels": [
  { "title": "Rack Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Average",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: IOUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Total Servers per Rack",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:110",
       "field": "RackLabel.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:108",
       "field": "RemoteAddr.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "RackLabel:$Rack",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "IDRAC Server Total  ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:55",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:53",
       "field": "RemoteAddr.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "CPUUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1775",
       "fake": true,
       "field": "RemoteAddr.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1758",
       "fake": true,
       "field": "Timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1700",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:228",
       "fake": true,
       "field": "RemoteAddr.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:102",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:100",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId:MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "fake": true,
       "field": "RemoteAddr.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:250",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:248",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId:IOUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Total Metrics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:55",
       "field": "RackLabel.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:53",
       "field": "MetricId.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "RackLabel:$Rack",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "IdracServer" },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 28 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 41 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 41 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 54 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 54 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 67 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 67 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 67 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 73 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 80 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 80 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 80 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 86 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Server Overview $IdracServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "CPU Usage Average",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 93 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: CPUUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Bandwidth Avg",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 93 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(Id: CUPS OR Id: SystemUsage) AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: MemoryUsage",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Voltages",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 93 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: VoltageReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Board  Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 93 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: TemperatureReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 93 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:951",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Id: Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: WattsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:516",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:213",
       "fake": true,
       "field": "Timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:949",
       "field": "MetricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Id:Sensor AND  RackLabel:$Rack AND RemoteAddr:$IdracServer AND MetricId: AmpsReading",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Network  $IdracServer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 99 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "TX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: TxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    },
    {
     "alias": "RX-{{ContextID.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "ContextID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:67",
       "field": "Timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:65",
       "field": "MetricValue",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:168",
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "Id: NICStatistics AND MetricId: RxBytes AND RackLabel:$Rack AND RemoteAddr:$IdracServer",
     "timeField": "Timestamp"
    }
   ]
  }
 ]
}