apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    release: {{ .Release.Name }}-haproxy
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}-haproxy
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}-haproxy
    spec:
      containers:
      - name: {{ .Release.Namespace }}-{{ .Release.Name }}-haproxy
        image: {{ .Values.haproxy.image }}
        imagePullPolicy: Always
        command: [ "/usr/local/etc/haproxy/haproxy.cfg/entry.sh" ]
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
        - mountPath: /etc/ssl/certs/cert.pem
          name: mycert
      volumes:
      - configMap:
          defaultMode: 420
          name: mycert
        name: mycert
      - name: haproxy-config-volume
        configMap:
          name: {{ .Release.Name }}
          defaultMode: 0744