
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "secrets_credentials" $ }}"
  labels:
    app: {{ template "timescaledb.fullname" . }}
    cluster-name: {{ template "timescaledb.fullname" . }}
type: Opaque
data:
  PATRONI_SUPERUSER_PASSWORD: {{ .Values.patroni.postgresql.authentication.superuser.password | b64enc }}
  PATRONI_REPLICATION_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  PATRONI_admin_PASSWORD: {{ randAlphaNum 16 | b64enc }}

